version: "3"

services:
  app:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    volumes:
      - .:/app/
      - /app/node_modules
    container_name: teslo-app-dev
    ports:
      - ${PORT}:${PORT}
    environment:
      HOST_NAME: ${HOST_NAME}
      MONGO_URL: ${MONGO_URL}
      JWT_SECRET_SEED: ${JWT_SECRET_SEED}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_PUBLIC_TAX_RATE: ${NEXT_PUBLIC_TAX_RATE}
      GITHUB_ID: ${GITHUB_ID}
      GITHUB_SECRET: ${GITHUB_SECRET}
      NEXT_PUBLIC_PAYPAL_CLIENT_ID: ${NEXT_PUBLIC_PAYPAL_CLIENT_ID}
      PAYPAL_SECRET: ${PAYPAL_SECRET}
      PAYPAL_OAUTH_URL: ${PAYPAL_OAUTH_URL}
      PAYPAL_ORDERS_URL: ${PAYPAL_ORDERS_URL}
      CLOUDINARY_URL: ${CLOUDINARY_URL}
      PORT: ${PORT}
      STAGE: ${STAGE}
    depends_on:
      - teslodb
  teslodb:
    image: mongo:5.0.0
    container_name: teslo-database-dev
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
