name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          major_pattern: "feat:"
          minor_pattern: "fix:"
          format: "${major}.${minor}.${patch}-prerelease${increment}"
        id: version

      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build Docker Image
        env:
          NEW_VERSION: ${{steps.version.outputs.version}}
          PORT: ${{env.PORT}}
          HOST_NAME: ${{env.HOST_NAME}}
          MONGO_URL: ${{secrets.MONGO_URL}}
          CLOUDINARY_URL: ${{secrets.CLOUDINARY_URL}}
          GH_ID: ${{secrets.GH_ID}}
          GH_SECRET: ${{secrets.GH_SECRET}}
          JWT_SECRET_SEED: ${{secrets.JWT_SECRET_SEED}}
          NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
          NEXT_PUBLIC_PAYPAL_CLIENT_ID: ${{secrets.NEXT_PUBLIC_PAYPAL_CLIENT_ID}}
          PAYPAL_OAUTH_URL: ${{secrets.PAYPAL_OAUTH_URL}}
          PAYPAL_ORDERS_URL: ${{secrets.PAYPAL_ORDERS_URL}}
          PAYPAL_SECRET: ${{secrets.PAYPAL_SECRET}}
          NEXT_PUBLIC_TAX_RATE: ${{env.NEXT_PUBLIC_TAX_RATE}}
          STAGE: ${{env.STAGE}}
        run: |
          docker build --build-arg PORT=$PORT --build-arg HOST_NAME=$HOST_NAME --build-arg MONGO_URL=$MONGO_URL --build-arg CLOUDINARY_URL=$CLOUDINARY_URL --build-arg GH_ID=$GH_ID --build-arg GH_SECRET=$GH_SECRET --build-arg JWT_SECRET_SEED=$JWT_SECRET_SEED --build-arg NEXTAUTH_SECRET=$NEXTAUTH_SECRET --build-arg NEXT_PUBLIC_PAYPAL_CLIENT_ID=$NEXT_PUBLIC_PAYPAL_CLIENT_ID --build-arg PAYPAL_OAUTH_URL=$PAYPAL_OAUTH_URL --build-arg PAYPAL_ORDERS_URL=$PAYPAL_ORDERS_URL --build-arg PAYPAL_SECRET=$PAYPAL_SECRET --build-arg NEXT_PUBLIC_TAX_RATE=$NEXT_PUBLIC_TAX_RATE --build-arg STAGE=$STAGE -t pablorodriguez88/teslo-shop-nextjs-app:$NEW_VERSION .
          docker build --build-arg PORT=$PORT --build-arg HOST_NAME=$HOST_NAME --build-arg MONGO_URL=$MONGO_URL --build-arg CLOUDINARY_URL=$CLOUDINARY_URL --build-arg GH_ID=$GH_ID --build-arg GH_SECRET=$GH_SECRET --build-arg JWT_SECRET_SEED=$JWT_SECRET_SEED --build-arg NEXTAUTH_SECRET=$NEXTAUTH_SECRET --build-arg NEXT_PUBLIC_PAYPAL_CLIENT_ID=$NEXT_PUBLIC_PAYPAL_CLIENT_ID --build-arg PAYPAL_OAUTH_URL=$PAYPAL_OAUTH_URL --build-arg PAYPAL_ORDERS_URL=$PAYPAL_ORDERS_URL --build-arg PAYPAL_SECRET=$PAYPAL_SECRET --build-arg NEXT_PUBLIC_TAX_RATE=$NEXT_PUBLIC_TAX_RATE --build-arg STAGE=$STAGE -t pablorodriguez88/teslo-shop-nextjs-app:latest .

      - name: Push Docker Image
        env:
          NEW_VERSION: ${{steps.version.outputs.version}}
        run: |
          docker push pablorodriguez88/teslo-shop-nextjs-app:$NEW_VERSION
          docker push pablorodriguez88/teslo-shop-nextjs-app:latest
